import Head from "next/head";
import Image from "next/image";
import img from '../../public/images/js-date-11.jpg'
export const metadata = {
    title: 'category',
    description: 'Generated by create next app',
  }
export default function Category() {
  return (
    <>
      <Head>
        category
      </Head>
      <h1 className="text-3xl font-semibold text-red-700">my category</h1>
        <Image src={img} width={400} height={400}/>
    </>
  );
}
